version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: loteria360-mysql
    environment:
      MYSQL_DATABASE: loteria360
      MYSQL_USER: loteria
      MYSQL_PASSWORD: loteria
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - loteria360-network

  adminer:
    image: adminer:4.8.1
    container_name: loteria360-adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - loteria360-network

volumes:
  mysql_data:
    driver: local

networks:
  loteria360-network:
    driver: bridge
