version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: loteria360-postgres
    environment:
      POSTGRES_DB: loteria360
      POSTGRES_USER: loteria
      POSTGRES_PASSWORD: loteria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loteria -d loteria360"]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: loteria360-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@loteria360.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
