spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loteria360?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: loteria
    password: loteria
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    com.loteria360: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
